# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - |
    julia --depwarn=error -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      if VERSION >= v"0.7.0-DEV.5183" && (isfile("Project.toml") || isfile("JuliaProject.toml"))
          Pkg.build(); Pkg.test(coverage=true)
      else
          Pkg.clone(pwd()); Pkg.build("CodecLz4"); Pkg.test("CodecLz4"; coverage=true)
      end'
after_success:
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("CodecLz4"))
      Pkg.add("Coverage"); using Coverage
      Codecov.submit(process_folder())'
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("CodecLz4"))
      Pkg.add("Documenter");
      include(joinpath("docs", "make.jl"))'
